# Generated by Django 5.2 on 2025-04-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
