# Generated by Django 5.2 on 2025-04-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, default='static\\profile_photo.png', null=True, upload_to='media/'),
        ),
    ]
