# Generated by Django 5.1.6 on 2025-04-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_alter_client_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, max_length=445, null=True),
        ),
    ]
