# Generated by Django 5.1.6 on 2025-04-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_alter_client_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='media\\profile_photo.png', upload_to='media/'),
        ),
    ]
