# Generated by Django 5.2 on 2025-04-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0009_message_client_message_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='client',
        ),
    ]
