# Generated by Django 5.2 on 2025-04-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0010_remove_message_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
