# Generated by Django 5.2 on 2025-04-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
