# Generated by Django 5.2 on 2025-05-02 08:21

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_alter_chatgroup_group_name_alter_chatgroup_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='photo',
            field=models.ImageField(default='media/chat_group_images/3.png', upload_to='media/'),
        ),
    ]
