# Generated by Django 5.2 on 2025-05-02 08:23

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_alter_chatgroup_group_name_alter_chatgroup_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='invite_code',
            field=models.CharField(blank=True, editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
